/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Phishing.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Phishing.Model
{
    /// <summary>
    /// Request to detect phishing from an email
    /// </summary>
    [DataContract]
    public partial class AdvancedEmailDetectionRequest :  IEquatable<AdvancedEmailDetectionRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AdvancedEmailDetectionRequest" /> class.
        /// </summary>
        /// <param name="fromEmailAddress">Email address of the sender.</param>
        /// <param name="toEmailAddress">Email address of the recipient.</param>
        /// <param name="subject">Subject of the email.</param>
        /// <param name="htmlBody">Body of the email in HTML, or text.</param>
        /// <param name="allowLowReputationSenders">Allow email from low reputation senders and domains.</param>
        /// <param name="allowSanctioned">True to allow sanctioned countries and certain known sanctioned entities, false otherwise (default).</param>
        /// <param name="customPolicyID">Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud.</param>
        /// <param name="inputEmailFile">Optional: Input email file bytes (EML, PDF, etc.).  If not provided, HtmlBody will be used instead..</param>
        public AdvancedEmailDetectionRequest(string fromEmailAddress = default(string), string toEmailAddress = default(string), string subject = default(string), string htmlBody = default(string), bool? allowLowReputationSenders = default(bool?), bool? allowSanctioned = default(bool?), string customPolicyID = default(string), byte[] inputEmailFile = default(byte[]))
        {
            this.FromEmailAddress = fromEmailAddress;
            this.ToEmailAddress = toEmailAddress;
            this.Subject = subject;
            this.HtmlBody = htmlBody;
            this.AllowLowReputationSenders = allowLowReputationSenders;
            this.AllowSanctioned = allowSanctioned;
            this.CustomPolicyID = customPolicyID;
            this.InputEmailFile = inputEmailFile;
        }
        
        /// <summary>
        /// Email address of the sender
        /// </summary>
        /// <value>Email address of the sender</value>
        [DataMember(Name="FromEmailAddress", EmitDefaultValue=false)]
        public string FromEmailAddress { get; set; }

        /// <summary>
        /// Email address of the recipient
        /// </summary>
        /// <value>Email address of the recipient</value>
        [DataMember(Name="ToEmailAddress", EmitDefaultValue=false)]
        public string ToEmailAddress { get; set; }

        /// <summary>
        /// Subject of the email
        /// </summary>
        /// <value>Subject of the email</value>
        [DataMember(Name="Subject", EmitDefaultValue=false)]
        public string Subject { get; set; }

        /// <summary>
        /// Body of the email in HTML, or text
        /// </summary>
        /// <value>Body of the email in HTML, or text</value>
        [DataMember(Name="HtmlBody", EmitDefaultValue=false)]
        public string HtmlBody { get; set; }

        /// <summary>
        /// Allow email from low reputation senders and domains
        /// </summary>
        /// <value>Allow email from low reputation senders and domains</value>
        [DataMember(Name="AllowLowReputationSenders", EmitDefaultValue=false)]
        public bool? AllowLowReputationSenders { get; set; }

        /// <summary>
        /// True to allow sanctioned countries and certain known sanctioned entities, false otherwise (default)
        /// </summary>
        /// <value>True to allow sanctioned countries and certain known sanctioned entities, false otherwise (default)</value>
        [DataMember(Name="AllowSanctioned", EmitDefaultValue=false)]
        public bool? AllowSanctioned { get; set; }

        /// <summary>
        /// Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud
        /// </summary>
        /// <value>Apply a Custom Policy for Phishing Enforcement by providing the ID; to create a Custom Policy,  navigate to the Cloudmersive Management Portal and select Custom Policies.  Requires Managed Instance or Private Cloud</value>
        [DataMember(Name="CustomPolicyID", EmitDefaultValue=false)]
        public string CustomPolicyID { get; set; }

        /// <summary>
        /// Optional: Input email file bytes (EML, PDF, etc.).  If not provided, HtmlBody will be used instead.
        /// </summary>
        /// <value>Optional: Input email file bytes (EML, PDF, etc.).  If not provided, HtmlBody will be used instead.</value>
        [DataMember(Name="InputEmailFile", EmitDefaultValue=false)]
        public byte[] InputEmailFile { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AdvancedEmailDetectionRequest {\n");
            sb.Append("  FromEmailAddress: ").Append(FromEmailAddress).Append("\n");
            sb.Append("  ToEmailAddress: ").Append(ToEmailAddress).Append("\n");
            sb.Append("  Subject: ").Append(Subject).Append("\n");
            sb.Append("  HtmlBody: ").Append(HtmlBody).Append("\n");
            sb.Append("  AllowLowReputationSenders: ").Append(AllowLowReputationSenders).Append("\n");
            sb.Append("  AllowSanctioned: ").Append(AllowSanctioned).Append("\n");
            sb.Append("  CustomPolicyID: ").Append(CustomPolicyID).Append("\n");
            sb.Append("  InputEmailFile: ").Append(InputEmailFile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AdvancedEmailDetectionRequest);
        }

        /// <summary>
        /// Returns true if AdvancedEmailDetectionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AdvancedEmailDetectionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AdvancedEmailDetectionRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.FromEmailAddress == input.FromEmailAddress ||
                    (this.FromEmailAddress != null &&
                    this.FromEmailAddress.Equals(input.FromEmailAddress))
                ) && 
                (
                    this.ToEmailAddress == input.ToEmailAddress ||
                    (this.ToEmailAddress != null &&
                    this.ToEmailAddress.Equals(input.ToEmailAddress))
                ) && 
                (
                    this.Subject == input.Subject ||
                    (this.Subject != null &&
                    this.Subject.Equals(input.Subject))
                ) && 
                (
                    this.HtmlBody == input.HtmlBody ||
                    (this.HtmlBody != null &&
                    this.HtmlBody.Equals(input.HtmlBody))
                ) && 
                (
                    this.AllowLowReputationSenders == input.AllowLowReputationSenders ||
                    (this.AllowLowReputationSenders != null &&
                    this.AllowLowReputationSenders.Equals(input.AllowLowReputationSenders))
                ) && 
                (
                    this.AllowSanctioned == input.AllowSanctioned ||
                    (this.AllowSanctioned != null &&
                    this.AllowSanctioned.Equals(input.AllowSanctioned))
                ) && 
                (
                    this.CustomPolicyID == input.CustomPolicyID ||
                    (this.CustomPolicyID != null &&
                    this.CustomPolicyID.Equals(input.CustomPolicyID))
                ) && 
                (
                    this.InputEmailFile == input.InputEmailFile ||
                    (this.InputEmailFile != null &&
                    this.InputEmailFile.Equals(input.InputEmailFile))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.FromEmailAddress != null)
                    hashCode = hashCode * 59 + this.FromEmailAddress.GetHashCode();
                if (this.ToEmailAddress != null)
                    hashCode = hashCode * 59 + this.ToEmailAddress.GetHashCode();
                if (this.Subject != null)
                    hashCode = hashCode * 59 + this.Subject.GetHashCode();
                if (this.HtmlBody != null)
                    hashCode = hashCode * 59 + this.HtmlBody.GetHashCode();
                if (this.AllowLowReputationSenders != null)
                    hashCode = hashCode * 59 + this.AllowLowReputationSenders.GetHashCode();
                if (this.AllowSanctioned != null)
                    hashCode = hashCode * 59 + this.AllowSanctioned.GetHashCode();
                if (this.CustomPolicyID != null)
                    hashCode = hashCode * 59 + this.CustomPolicyID.GetHashCode();
                if (this.InputEmailFile != null)
                    hashCode = hashCode * 59 + this.InputEmailFile.GetHashCode();
                return hashCode;
            }
        }
    }

}
