/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Phishing.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Phishing.Model
{
    /// <summary>
    /// Request data for the advanced api batch request
    /// </summary>
    [DataContract]
    public partial class PhishingUrlAdvancedRequestBatch :  IEquatable<PhishingUrlAdvancedRequestBatch>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingUrlAdvancedRequestBatch" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PhishingUrlAdvancedRequestBatch() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingUrlAdvancedRequestBatch" /> class.
        /// </summary>
        /// <param name="urls">Collection of all urls to check (required).</param>
        /// <param name="allowList">The caller may specify a collection of   hosts or domains which are always considered safe.&lt;br /&gt;  This is to allow internal sites to be marked as safe.</param>
        /// <param name="blockList">The caller may specify a collection of   hosts or domains which are always considered unsafe.&lt;br /&gt;  This is to allow internal sites to be marked as safe.</param>
        public PhishingUrlAdvancedRequestBatch(List<string> urls = default(List<string>), List<string> allowList = default(List<string>), List<string> blockList = default(List<string>))
        {
            // to ensure "urls" is required (not null)
            if (urls == null)
            {
                throw new InvalidDataException("urls is a required property for PhishingUrlAdvancedRequestBatch and cannot be null");
            }
            else
            {
                this.Urls = urls;
            }
            this.AllowList = allowList;
            this.BlockList = blockList;
        }
        
        /// <summary>
        /// Collection of all urls to check
        /// </summary>
        /// <value>Collection of all urls to check</value>
        [DataMember(Name="Urls", EmitDefaultValue=false)]
        public List<string> Urls { get; set; }

        /// <summary>
        /// The caller may specify a collection of   hosts or domains which are always considered safe.&lt;br /&gt;  This is to allow internal sites to be marked as safe
        /// </summary>
        /// <value>The caller may specify a collection of   hosts or domains which are always considered safe.&lt;br /&gt;  This is to allow internal sites to be marked as safe</value>
        [DataMember(Name="AllowList", EmitDefaultValue=false)]
        public List<string> AllowList { get; set; }

        /// <summary>
        /// The caller may specify a collection of   hosts or domains which are always considered unsafe.&lt;br /&gt;  This is to allow internal sites to be marked as safe
        /// </summary>
        /// <value>The caller may specify a collection of   hosts or domains which are always considered unsafe.&lt;br /&gt;  This is to allow internal sites to be marked as safe</value>
        [DataMember(Name="BlockList", EmitDefaultValue=false)]
        public List<string> BlockList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhishingUrlAdvancedRequestBatch {\n");
            sb.Append("  Urls: ").Append(Urls).Append("\n");
            sb.Append("  AllowList: ").Append(AllowList).Append("\n");
            sb.Append("  BlockList: ").Append(BlockList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PhishingUrlAdvancedRequestBatch);
        }

        /// <summary>
        /// Returns true if PhishingUrlAdvancedRequestBatch instances are equal
        /// </summary>
        /// <param name="input">Instance of PhishingUrlAdvancedRequestBatch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhishingUrlAdvancedRequestBatch input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Urls == input.Urls ||
                    this.Urls != null &&
                    this.Urls.SequenceEqual(input.Urls)
                ) && 
                (
                    this.AllowList == input.AllowList ||
                    this.AllowList != null &&
                    this.AllowList.SequenceEqual(input.AllowList)
                ) && 
                (
                    this.BlockList == input.BlockList ||
                    this.BlockList != null &&
                    this.BlockList.SequenceEqual(input.BlockList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Urls != null)
                    hashCode = hashCode * 59 + this.Urls.GetHashCode();
                if (this.AllowList != null)
                    hashCode = hashCode * 59 + this.AllowList.GetHashCode();
                if (this.BlockList != null)
                    hashCode = hashCode * 59 + this.BlockList.GetHashCode();
                return hashCode;
            }
        }
    }

}
