/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Phishing.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Phishing.Model
{
    /// <summary>
    /// Response for the phishing validation apis
    /// </summary>
    [DataContract]
    public partial class PhishingUrlResponse :  IEquatable<PhishingUrlResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingUrlResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">Specifies if the url (or its host or domain) passed all the checks or not..</param>
        /// <param name="risk">Risk value from 0.0 - 1.0. Higher numbers are a higher risk  &lt;br /&gt;Anything below 0.3 should be considered safe. Anything above 0.7 should be considered a significant risk. &lt;br /&gt;  A score of 1.0 indicates the url, host, or domain failed significant safety checks.&lt;br /&gt;  If a url passes all the tests for the basic api, the risk will be 0.7. If a url passes all the tests for the advanced api, the risk will be 0.2..</param>
        /// <param name="containsThreatUrl">Specifies if the full url with query parameters and fragment is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the full url..</param>
        /// <param name="containsThreatHost">Specifies if the host of the url (i.e. &#x60;&#x60;&#x60;mysite.hostingsite.com&#x60;&#x60;&#x60; for a url of &#x60;&#x60;&#x60;https://mysite.hostingsite.com/index.html&#x60;&#x60;&#x60;) is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the host.</param>
        /// <param name="containsThreatDomain">Specifies if the registerable domain of the url (i.e. &#x60;&#x60;&#x60;hostingsite.com&#x60;&#x60;&#x60; for a url of &#x60;&#x60;&#x60;https://mysite.hostingsite.com/index.html&#x60;&#x60;&#x60;) is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the domain.</param>
        /// <param name="inputUrl">Input URL that was scanned.</param>
        public PhishingUrlResponse(bool? cleanResult = default(bool?), double? risk = default(double?), bool? containsThreatUrl = default(bool?), bool? containsThreatHost = default(bool?), bool? containsThreatDomain = default(bool?), string inputUrl = default(string))
        {
            this.CleanResult = cleanResult;
            this.Risk = risk;
            this.ContainsThreatUrl = containsThreatUrl;
            this.ContainsThreatHost = containsThreatHost;
            this.ContainsThreatDomain = containsThreatDomain;
            this.InputUrl = inputUrl;
        }
        
        /// <summary>
        /// Specifies if the url (or its host or domain) passed all the checks or not.
        /// </summary>
        /// <value>Specifies if the url (or its host or domain) passed all the checks or not.</value>
        [DataMember(Name="CleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// Risk value from 0.0 - 1.0. Higher numbers are a higher risk  &lt;br /&gt;Anything below 0.3 should be considered safe. Anything above 0.7 should be considered a significant risk. &lt;br /&gt;  A score of 1.0 indicates the url, host, or domain failed significant safety checks.&lt;br /&gt;  If a url passes all the tests for the basic api, the risk will be 0.7. If a url passes all the tests for the advanced api, the risk will be 0.2.
        /// </summary>
        /// <value>Risk value from 0.0 - 1.0. Higher numbers are a higher risk  &lt;br /&gt;Anything below 0.3 should be considered safe. Anything above 0.7 should be considered a significant risk. &lt;br /&gt;  A score of 1.0 indicates the url, host, or domain failed significant safety checks.&lt;br /&gt;  If a url passes all the tests for the basic api, the risk will be 0.7. If a url passes all the tests for the advanced api, the risk will be 0.2.</value>
        [DataMember(Name="Risk", EmitDefaultValue=false)]
        public double? Risk { get; set; }

        /// <summary>
        /// Specifies if the full url with query parameters and fragment is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the full url.
        /// </summary>
        /// <value>Specifies if the full url with query parameters and fragment is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the full url.</value>
        [DataMember(Name="ContainsThreatUrl", EmitDefaultValue=false)]
        public bool? ContainsThreatUrl { get; set; }

        /// <summary>
        /// Specifies if the host of the url (i.e. &#x60;&#x60;&#x60;mysite.hostingsite.com&#x60;&#x60;&#x60; for a url of &#x60;&#x60;&#x60;https://mysite.hostingsite.com/index.html&#x60;&#x60;&#x60;) is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the host
        /// </summary>
        /// <value>Specifies if the host of the url (i.e. &#x60;&#x60;&#x60;mysite.hostingsite.com&#x60;&#x60;&#x60; for a url of &#x60;&#x60;&#x60;https://mysite.hostingsite.com/index.html&#x60;&#x60;&#x60;) is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the host</value>
        [DataMember(Name="ContainsThreatHost", EmitDefaultValue=false)]
        public bool? ContainsThreatHost { get; set; }

        /// <summary>
        /// Specifies if the registerable domain of the url (i.e. &#x60;&#x60;&#x60;hostingsite.com&#x60;&#x60;&#x60; for a url of &#x60;&#x60;&#x60;https://mysite.hostingsite.com/index.html&#x60;&#x60;&#x60;) is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the domain
        /// </summary>
        /// <value>Specifies if the registerable domain of the url (i.e. &#x60;&#x60;&#x60;hostingsite.com&#x60;&#x60;&#x60; for a url of &#x60;&#x60;&#x60;https://mysite.hostingsite.com/index.html&#x60;&#x60;&#x60;) is a phishing threat  &lt;br /&gt;The advanced api performs more checks on the domain</value>
        [DataMember(Name="ContainsThreatDomain", EmitDefaultValue=false)]
        public bool? ContainsThreatDomain { get; set; }

        /// <summary>
        /// Input URL that was scanned
        /// </summary>
        /// <value>Input URL that was scanned</value>
        [DataMember(Name="InputUrl", EmitDefaultValue=false)]
        public string InputUrl { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhishingUrlResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  Risk: ").Append(Risk).Append("\n");
            sb.Append("  ContainsThreatUrl: ").Append(ContainsThreatUrl).Append("\n");
            sb.Append("  ContainsThreatHost: ").Append(ContainsThreatHost).Append("\n");
            sb.Append("  ContainsThreatDomain: ").Append(ContainsThreatDomain).Append("\n");
            sb.Append("  InputUrl: ").Append(InputUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PhishingUrlResponse);
        }

        /// <summary>
        /// Returns true if PhishingUrlResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PhishingUrlResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhishingUrlResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                ) && 
                (
                    this.Risk == input.Risk ||
                    (this.Risk != null &&
                    this.Risk.Equals(input.Risk))
                ) && 
                (
                    this.ContainsThreatUrl == input.ContainsThreatUrl ||
                    (this.ContainsThreatUrl != null &&
                    this.ContainsThreatUrl.Equals(input.ContainsThreatUrl))
                ) && 
                (
                    this.ContainsThreatHost == input.ContainsThreatHost ||
                    (this.ContainsThreatHost != null &&
                    this.ContainsThreatHost.Equals(input.ContainsThreatHost))
                ) && 
                (
                    this.ContainsThreatDomain == input.ContainsThreatDomain ||
                    (this.ContainsThreatDomain != null &&
                    this.ContainsThreatDomain.Equals(input.ContainsThreatDomain))
                ) && 
                (
                    this.InputUrl == input.InputUrl ||
                    (this.InputUrl != null &&
                    this.InputUrl.Equals(input.InputUrl))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                if (this.Risk != null)
                    hashCode = hashCode * 59 + this.Risk.GetHashCode();
                if (this.ContainsThreatUrl != null)
                    hashCode = hashCode * 59 + this.ContainsThreatUrl.GetHashCode();
                if (this.ContainsThreatHost != null)
                    hashCode = hashCode * 59 + this.ContainsThreatHost.GetHashCode();
                if (this.ContainsThreatDomain != null)
                    hashCode = hashCode * 59 + this.ContainsThreatDomain.GetHashCode();
                if (this.InputUrl != null)
                    hashCode = hashCode * 59 + this.InputUrl.GetHashCode();
                return hashCode;
            }
        }
    }

}
