/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Phishing.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Phishing.Model
{
    /// <summary>
    /// Result of detecting phishing using AI
    /// </summary>
    [DataContract]
    public partial class PhishingDetectionEmailAdvancedResponse :  IEquatable<PhishingDetectionEmailAdvancedResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionEmailAdvancedResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if the result is not phishing (clean), and false otherwise.</param>
        /// <param name="phishingRiskLevel">Overall phishing risk level between 0.0 and 1.0.</param>
        /// <param name="spamRiskLevel">Overall phishing spam level between 0.0 and 1.0.</param>
        /// <param name="containsLowReputationSender">True if the input email is from a low reputation sender.</param>
        /// <param name="containsPhishing">True if the input email contains phishing threat risks, false otherwise.</param>
        /// <param name="containsSpam">True if the email contains phishing threat risks, false otherwise.</param>
        /// <param name="containsUnsolicitedSales">True if the input email contains unsolicited sales, false otherwise.</param>
        /// <param name="containsPromotionalContent">True if the input email contains promotional content, false otherwise.</param>
        /// <param name="containsPhishingAttempt">True if the input email contains a phishing attempt, false otherwise.</param>
        /// <param name="analysisRationale">Rationale for why the conclusion was formed.</param>
        public PhishingDetectionEmailAdvancedResponse(bool? cleanResult = default(bool?), double? phishingRiskLevel = default(double?), double? spamRiskLevel = default(double?), bool? containsLowReputationSender = default(bool?), bool? containsPhishing = default(bool?), bool? containsSpam = default(bool?), bool? containsUnsolicitedSales = default(bool?), bool? containsPromotionalContent = default(bool?), bool? containsPhishingAttempt = default(bool?), string analysisRationale = default(string))
        {
            this.CleanResult = cleanResult;
            this.PhishingRiskLevel = phishingRiskLevel;
            this.SpamRiskLevel = spamRiskLevel;
            this.ContainsLowReputationSender = containsLowReputationSender;
            this.ContainsPhishing = containsPhishing;
            this.ContainsSpam = containsSpam;
            this.ContainsUnsolicitedSales = containsUnsolicitedSales;
            this.ContainsPromotionalContent = containsPromotionalContent;
            this.ContainsPhishingAttempt = containsPhishingAttempt;
            this.AnalysisRationale = analysisRationale;
        }
        
        /// <summary>
        /// True if the result is not phishing (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not phishing (clean), and false otherwise</value>
        [DataMember(Name="CleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// Overall phishing risk level between 0.0 and 1.0
        /// </summary>
        /// <value>Overall phishing risk level between 0.0 and 1.0</value>
        [DataMember(Name="PhishingRiskLevel", EmitDefaultValue=false)]
        public double? PhishingRiskLevel { get; set; }

        /// <summary>
        /// Overall phishing spam level between 0.0 and 1.0
        /// </summary>
        /// <value>Overall phishing spam level between 0.0 and 1.0</value>
        [DataMember(Name="SpamRiskLevel", EmitDefaultValue=false)]
        public double? SpamRiskLevel { get; set; }

        /// <summary>
        /// True if the input email is from a low reputation sender
        /// </summary>
        /// <value>True if the input email is from a low reputation sender</value>
        [DataMember(Name="ContainsLowReputationSender", EmitDefaultValue=false)]
        public bool? ContainsLowReputationSender { get; set; }

        /// <summary>
        /// True if the input email contains phishing threat risks, false otherwise
        /// </summary>
        /// <value>True if the input email contains phishing threat risks, false otherwise</value>
        [DataMember(Name="ContainsPhishing", EmitDefaultValue=false)]
        public bool? ContainsPhishing { get; set; }

        /// <summary>
        /// True if the email contains phishing threat risks, false otherwise
        /// </summary>
        /// <value>True if the email contains phishing threat risks, false otherwise</value>
        [DataMember(Name="ContainsSpam", EmitDefaultValue=false)]
        public bool? ContainsSpam { get; set; }

        /// <summary>
        /// True if the input email contains unsolicited sales, false otherwise
        /// </summary>
        /// <value>True if the input email contains unsolicited sales, false otherwise</value>
        [DataMember(Name="ContainsUnsolicitedSales", EmitDefaultValue=false)]
        public bool? ContainsUnsolicitedSales { get; set; }

        /// <summary>
        /// True if the input email contains promotional content, false otherwise
        /// </summary>
        /// <value>True if the input email contains promotional content, false otherwise</value>
        [DataMember(Name="ContainsPromotionalContent", EmitDefaultValue=false)]
        public bool? ContainsPromotionalContent { get; set; }

        /// <summary>
        /// True if the input email contains a phishing attempt, false otherwise
        /// </summary>
        /// <value>True if the input email contains a phishing attempt, false otherwise</value>
        [DataMember(Name="ContainsPhishingAttempt", EmitDefaultValue=false)]
        public bool? ContainsPhishingAttempt { get; set; }

        /// <summary>
        /// Rationale for why the conclusion was formed
        /// </summary>
        /// <value>Rationale for why the conclusion was formed</value>
        [DataMember(Name="AnalysisRationale", EmitDefaultValue=false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhishingDetectionEmailAdvancedResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  PhishingRiskLevel: ").Append(PhishingRiskLevel).Append("\n");
            sb.Append("  SpamRiskLevel: ").Append(SpamRiskLevel).Append("\n");
            sb.Append("  ContainsLowReputationSender: ").Append(ContainsLowReputationSender).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("  ContainsSpam: ").Append(ContainsSpam).Append("\n");
            sb.Append("  ContainsUnsolicitedSales: ").Append(ContainsUnsolicitedSales).Append("\n");
            sb.Append("  ContainsPromotionalContent: ").Append(ContainsPromotionalContent).Append("\n");
            sb.Append("  ContainsPhishingAttempt: ").Append(ContainsPhishingAttempt).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PhishingDetectionEmailAdvancedResponse);
        }

        /// <summary>
        /// Returns true if PhishingDetectionEmailAdvancedResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PhishingDetectionEmailAdvancedResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhishingDetectionEmailAdvancedResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                ) && 
                (
                    this.PhishingRiskLevel == input.PhishingRiskLevel ||
                    (this.PhishingRiskLevel != null &&
                    this.PhishingRiskLevel.Equals(input.PhishingRiskLevel))
                ) && 
                (
                    this.SpamRiskLevel == input.SpamRiskLevel ||
                    (this.SpamRiskLevel != null &&
                    this.SpamRiskLevel.Equals(input.SpamRiskLevel))
                ) && 
                (
                    this.ContainsLowReputationSender == input.ContainsLowReputationSender ||
                    (this.ContainsLowReputationSender != null &&
                    this.ContainsLowReputationSender.Equals(input.ContainsLowReputationSender))
                ) && 
                (
                    this.ContainsPhishing == input.ContainsPhishing ||
                    (this.ContainsPhishing != null &&
                    this.ContainsPhishing.Equals(input.ContainsPhishing))
                ) && 
                (
                    this.ContainsSpam == input.ContainsSpam ||
                    (this.ContainsSpam != null &&
                    this.ContainsSpam.Equals(input.ContainsSpam))
                ) && 
                (
                    this.ContainsUnsolicitedSales == input.ContainsUnsolicitedSales ||
                    (this.ContainsUnsolicitedSales != null &&
                    this.ContainsUnsolicitedSales.Equals(input.ContainsUnsolicitedSales))
                ) && 
                (
                    this.ContainsPromotionalContent == input.ContainsPromotionalContent ||
                    (this.ContainsPromotionalContent != null &&
                    this.ContainsPromotionalContent.Equals(input.ContainsPromotionalContent))
                ) && 
                (
                    this.ContainsPhishingAttempt == input.ContainsPhishingAttempt ||
                    (this.ContainsPhishingAttempt != null &&
                    this.ContainsPhishingAttempt.Equals(input.ContainsPhishingAttempt))
                ) && 
                (
                    this.AnalysisRationale == input.AnalysisRationale ||
                    (this.AnalysisRationale != null &&
                    this.AnalysisRationale.Equals(input.AnalysisRationale))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                if (this.PhishingRiskLevel != null)
                    hashCode = hashCode * 59 + this.PhishingRiskLevel.GetHashCode();
                if (this.SpamRiskLevel != null)
                    hashCode = hashCode * 59 + this.SpamRiskLevel.GetHashCode();
                if (this.ContainsLowReputationSender != null)
                    hashCode = hashCode * 59 + this.ContainsLowReputationSender.GetHashCode();
                if (this.ContainsPhishing != null)
                    hashCode = hashCode * 59 + this.ContainsPhishing.GetHashCode();
                if (this.ContainsSpam != null)
                    hashCode = hashCode * 59 + this.ContainsSpam.GetHashCode();
                if (this.ContainsUnsolicitedSales != null)
                    hashCode = hashCode * 59 + this.ContainsUnsolicitedSales.GetHashCode();
                if (this.ContainsPromotionalContent != null)
                    hashCode = hashCode * 59 + this.ContainsPromotionalContent.GetHashCode();
                if (this.ContainsPhishingAttempt != null)
                    hashCode = hashCode * 59 + this.ContainsPhishingAttempt.GetHashCode();
                if (this.AnalysisRationale != null)
                    hashCode = hashCode * 59 + this.AnalysisRationale.GetHashCode();
                return hashCode;
            }
        }
    }

}
