/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Phishing.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Phishing.Model
{
    /// <summary>
    /// Result of detecting phishing using AI for basic text string analysis
    /// </summary>
    [DataContract]
    public partial class PhishingDetectionTextStringResponse :  IEquatable<PhishingDetectionTextStringResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionTextStringResponse" /> class.
        /// </summary>
        /// <param name="cleanResult">True if the result is not phishing (clean), and false otherwise.</param>
        /// <param name="confidenceLevel">Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence.</param>
        /// <param name="analysisRationale">Rationale for why the conclusion was formed.</param>
        public PhishingDetectionTextStringResponse(bool? cleanResult = default(bool?), double? confidenceLevel = default(double?), string analysisRationale = default(string))
        {
            this.CleanResult = cleanResult;
            this.ConfidenceLevel = confidenceLevel;
            this.AnalysisRationale = analysisRationale;
        }
        
        /// <summary>
        /// True if the result is not phishing (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not phishing (clean), and false otherwise</value>
        [DataMember(Name="CleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence
        /// </summary>
        /// <value>Confidence level between 0.0 and 1.0 where values over 0.9 indicate high confidence</value>
        [DataMember(Name="ConfidenceLevel", EmitDefaultValue=false)]
        public double? ConfidenceLevel { get; set; }

        /// <summary>
        /// Rationale for why the conclusion was formed
        /// </summary>
        /// <value>Rationale for why the conclusion was formed</value>
        [DataMember(Name="AnalysisRationale", EmitDefaultValue=false)]
        public string AnalysisRationale { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PhishingDetectionTextStringResponse {\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  ConfidenceLevel: ").Append(ConfidenceLevel).Append("\n");
            sb.Append("  AnalysisRationale: ").Append(AnalysisRationale).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PhishingDetectionTextStringResponse);
        }

        /// <summary>
        /// Returns true if PhishingDetectionTextStringResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PhishingDetectionTextStringResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PhishingDetectionTextStringResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                ) && 
                (
                    this.ConfidenceLevel == input.ConfidenceLevel ||
                    (this.ConfidenceLevel != null &&
                    this.ConfidenceLevel.Equals(input.ConfidenceLevel))
                ) && 
                (
                    this.AnalysisRationale == input.AnalysisRationale ||
                    (this.AnalysisRationale != null &&
                    this.AnalysisRationale.Equals(input.AnalysisRationale))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                if (this.ConfidenceLevel != null)
                    hashCode = hashCode * 59 + this.ConfidenceLevel.GetHashCode();
                if (this.AnalysisRationale != null)
                    hashCode = hashCode * 59 + this.AnalysisRationale.GetHashCode();
                return hashCode;
            }
        }
    }

}
