/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Phishing.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Phishing.Model
{
    /// <summary>
    /// A single message in the prior conversation history
    /// </summary>
    [DataContract]
    public partial class PriorHistoryItem :  IEquatable<PriorHistoryItem>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PriorHistoryItem" /> class.
        /// </summary>
        /// <param name="inputString">The text content of this historical message.</param>
        /// <param name="fromName">Optional: Name of the sender.</param>
        /// <param name="toName">Optional: Name of the recipient.</param>
        /// <param name="fromPhoneNumber">Optional: Phone number of the sender.</param>
        /// <param name="toPhoneNumber">Optional: Phone number of the recipient.</param>
        /// <param name="fromEmailAddress">Optional: Email address of the sender.</param>
        /// <param name="toEmailAddress">Optional: Email address of the recipient.</param>
        /// <param name="trustedParty">Optional: True if this message is from a trusted party (such as our own company), false otherwise.</param>
        public PriorHistoryItem(string inputString = default(string), string fromName = default(string), string toName = default(string), string fromPhoneNumber = default(string), string toPhoneNumber = default(string), string fromEmailAddress = default(string), string toEmailAddress = default(string), bool? trustedParty = default(bool?))
        {
            this.InputString = inputString;
            this.FromName = fromName;
            this.ToName = toName;
            this.FromPhoneNumber = fromPhoneNumber;
            this.ToPhoneNumber = toPhoneNumber;
            this.FromEmailAddress = fromEmailAddress;
            this.ToEmailAddress = toEmailAddress;
            this.TrustedParty = trustedParty;
        }
        
        /// <summary>
        /// The text content of this historical message
        /// </summary>
        /// <value>The text content of this historical message</value>
        [DataMember(Name="InputString", EmitDefaultValue=false)]
        public string InputString { get; set; }

        /// <summary>
        /// Optional: Name of the sender
        /// </summary>
        /// <value>Optional: Name of the sender</value>
        [DataMember(Name="FromName", EmitDefaultValue=false)]
        public string FromName { get; set; }

        /// <summary>
        /// Optional: Name of the recipient
        /// </summary>
        /// <value>Optional: Name of the recipient</value>
        [DataMember(Name="ToName", EmitDefaultValue=false)]
        public string ToName { get; set; }

        /// <summary>
        /// Optional: Phone number of the sender
        /// </summary>
        /// <value>Optional: Phone number of the sender</value>
        [DataMember(Name="FromPhoneNumber", EmitDefaultValue=false)]
        public string FromPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Phone number of the recipient
        /// </summary>
        /// <value>Optional: Phone number of the recipient</value>
        [DataMember(Name="ToPhoneNumber", EmitDefaultValue=false)]
        public string ToPhoneNumber { get; set; }

        /// <summary>
        /// Optional: Email address of the sender
        /// </summary>
        /// <value>Optional: Email address of the sender</value>
        [DataMember(Name="FromEmailAddress", EmitDefaultValue=false)]
        public string FromEmailAddress { get; set; }

        /// <summary>
        /// Optional: Email address of the recipient
        /// </summary>
        /// <value>Optional: Email address of the recipient</value>
        [DataMember(Name="ToEmailAddress", EmitDefaultValue=false)]
        public string ToEmailAddress { get; set; }

        /// <summary>
        /// Optional: True if this message is from a trusted party (such as our own company), false otherwise
        /// </summary>
        /// <value>Optional: True if this message is from a trusted party (such as our own company), false otherwise</value>
        [DataMember(Name="TrustedParty", EmitDefaultValue=false)]
        public bool? TrustedParty { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PriorHistoryItem {\n");
            sb.Append("  InputString: ").Append(InputString).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ToName: ").Append(ToName).Append("\n");
            sb.Append("  FromPhoneNumber: ").Append(FromPhoneNumber).Append("\n");
            sb.Append("  ToPhoneNumber: ").Append(ToPhoneNumber).Append("\n");
            sb.Append("  FromEmailAddress: ").Append(FromEmailAddress).Append("\n");
            sb.Append("  ToEmailAddress: ").Append(ToEmailAddress).Append("\n");
            sb.Append("  TrustedParty: ").Append(TrustedParty).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PriorHistoryItem);
        }

        /// <summary>
        /// Returns true if PriorHistoryItem instances are equal
        /// </summary>
        /// <param name="input">Instance of PriorHistoryItem to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PriorHistoryItem input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.InputString == input.InputString ||
                    (this.InputString != null &&
                    this.InputString.Equals(input.InputString))
                ) && 
                (
                    this.FromName == input.FromName ||
                    (this.FromName != null &&
                    this.FromName.Equals(input.FromName))
                ) && 
                (
                    this.ToName == input.ToName ||
                    (this.ToName != null &&
                    this.ToName.Equals(input.ToName))
                ) && 
                (
                    this.FromPhoneNumber == input.FromPhoneNumber ||
                    (this.FromPhoneNumber != null &&
                    this.FromPhoneNumber.Equals(input.FromPhoneNumber))
                ) && 
                (
                    this.ToPhoneNumber == input.ToPhoneNumber ||
                    (this.ToPhoneNumber != null &&
                    this.ToPhoneNumber.Equals(input.ToPhoneNumber))
                ) && 
                (
                    this.FromEmailAddress == input.FromEmailAddress ||
                    (this.FromEmailAddress != null &&
                    this.FromEmailAddress.Equals(input.FromEmailAddress))
                ) && 
                (
                    this.ToEmailAddress == input.ToEmailAddress ||
                    (this.ToEmailAddress != null &&
                    this.ToEmailAddress.Equals(input.ToEmailAddress))
                ) && 
                (
                    this.TrustedParty == input.TrustedParty ||
                    (this.TrustedParty != null &&
                    this.TrustedParty.Equals(input.TrustedParty))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.InputString != null)
                    hashCode = hashCode * 59 + this.InputString.GetHashCode();
                if (this.FromName != null)
                    hashCode = hashCode * 59 + this.FromName.GetHashCode();
                if (this.ToName != null)
                    hashCode = hashCode * 59 + this.ToName.GetHashCode();
                if (this.FromPhoneNumber != null)
                    hashCode = hashCode * 59 + this.FromPhoneNumber.GetHashCode();
                if (this.ToPhoneNumber != null)
                    hashCode = hashCode * 59 + this.ToPhoneNumber.GetHashCode();
                if (this.FromEmailAddress != null)
                    hashCode = hashCode * 59 + this.FromEmailAddress.GetHashCode();
                if (this.ToEmailAddress != null)
                    hashCode = hashCode * 59 + this.ToEmailAddress.GetHashCode();
                if (this.TrustedParty != null)
                    hashCode = hashCode * 59 + this.TrustedParty.GetHashCode();
                return hashCode;
            }
        }
    }

}
