/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Cloudmersive.APIClient.NETCore.Phishing.Client.SwaggerDateConverter;

namespace Cloudmersive.APIClient.NETCore.Phishing.Model
{
    /// <summary>
    /// Result of analyzing an individual URL found in text
    /// </summary>
    [DataContract]
    public partial class UnsafeUrlResult :  IEquatable<UnsafeUrlResult>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UnsafeUrlResult" /> class.
        /// </summary>
        /// <param name="url">The URL that was detected and analyzed.</param>
        /// <param name="cleanResult">True if the result is not phishing (clean), and false otherwise.</param>
        /// <param name="isSsrfThreat">True if the URL is an SSRF threat.</param>
        /// <param name="containsPhishing">True if the URL contains phishing threat risks, false otherwise.</param>
        /// <param name="containsPhishingAttempt">True if the URL contains a phishing attempt, false otherwise.</param>
        public UnsafeUrlResult(string url = default(string), bool? cleanResult = default(bool?), bool? isSsrfThreat = default(bool?), bool? containsPhishing = default(bool?), bool? containsPhishingAttempt = default(bool?))
        {
            this.Url = url;
            this.CleanResult = cleanResult;
            this.IsSsrfThreat = isSsrfThreat;
            this.ContainsPhishing = containsPhishing;
            this.ContainsPhishingAttempt = containsPhishingAttempt;
        }
        
        /// <summary>
        /// The URL that was detected and analyzed
        /// </summary>
        /// <value>The URL that was detected and analyzed</value>
        [DataMember(Name="Url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// True if the result is not phishing (clean), and false otherwise
        /// </summary>
        /// <value>True if the result is not phishing (clean), and false otherwise</value>
        [DataMember(Name="CleanResult", EmitDefaultValue=false)]
        public bool? CleanResult { get; set; }

        /// <summary>
        /// True if the URL is an SSRF threat
        /// </summary>
        /// <value>True if the URL is an SSRF threat</value>
        [DataMember(Name="IsSsrfThreat", EmitDefaultValue=false)]
        public bool? IsSsrfThreat { get; set; }

        /// <summary>
        /// True if the URL contains phishing threat risks, false otherwise
        /// </summary>
        /// <value>True if the URL contains phishing threat risks, false otherwise</value>
        [DataMember(Name="ContainsPhishing", EmitDefaultValue=false)]
        public bool? ContainsPhishing { get; set; }

        /// <summary>
        /// True if the URL contains a phishing attempt, false otherwise
        /// </summary>
        /// <value>True if the URL contains a phishing attempt, false otherwise</value>
        [DataMember(Name="ContainsPhishingAttempt", EmitDefaultValue=false)]
        public bool? ContainsPhishingAttempt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UnsafeUrlResult {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  CleanResult: ").Append(CleanResult).Append("\n");
            sb.Append("  IsSsrfThreat: ").Append(IsSsrfThreat).Append("\n");
            sb.Append("  ContainsPhishing: ").Append(ContainsPhishing).Append("\n");
            sb.Append("  ContainsPhishingAttempt: ").Append(ContainsPhishingAttempt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UnsafeUrlResult);
        }

        /// <summary>
        /// Returns true if UnsafeUrlResult instances are equal
        /// </summary>
        /// <param name="input">Instance of UnsafeUrlResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UnsafeUrlResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.CleanResult == input.CleanResult ||
                    (this.CleanResult != null &&
                    this.CleanResult.Equals(input.CleanResult))
                ) && 
                (
                    this.IsSsrfThreat == input.IsSsrfThreat ||
                    (this.IsSsrfThreat != null &&
                    this.IsSsrfThreat.Equals(input.IsSsrfThreat))
                ) && 
                (
                    this.ContainsPhishing == input.ContainsPhishing ||
                    (this.ContainsPhishing != null &&
                    this.ContainsPhishing.Equals(input.ContainsPhishing))
                ) && 
                (
                    this.ContainsPhishingAttempt == input.ContainsPhishingAttempt ||
                    (this.ContainsPhishingAttempt != null &&
                    this.ContainsPhishingAttempt.Equals(input.ContainsPhishingAttempt))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.CleanResult != null)
                    hashCode = hashCode * 59 + this.CleanResult.GetHashCode();
                if (this.IsSsrfThreat != null)
                    hashCode = hashCode * 59 + this.IsSsrfThreat.GetHashCode();
                if (this.ContainsPhishing != null)
                    hashCode = hashCode * 59 + this.ContainsPhishing.GetHashCode();
                if (this.ContainsPhishingAttempt != null)
                    hashCode = hashCode * 59 + this.ContainsPhishingAttempt.GetHashCode();
                return hashCode;
            }
        }
    }

}
