/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.Phishing.Client;
using Cloudmersive.APIClient.NETCore.Phishing.Model;

namespace Cloudmersive.APIClient.NETCore.Phishing.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPhishingUrlBatchApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>PhishingUrlAdvancedResponseBatch</returns>
        PhishingUrlAdvancedResponseBatch PhishingUrlAdvancedBatchPost (PhishingUrlAdvancedRequestBatch body = null);

        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of PhishingUrlAdvancedResponseBatch</returns>
        ApiResponse<PhishingUrlAdvancedResponseBatch> PhishingUrlAdvancedBatchPostWithHttpInfo (PhishingUrlAdvancedRequestBatch body = null);
        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>PhishingUrlResponseBatch</returns>
        PhishingUrlResponseBatch PhishingUrlBatchPost (List<PhishingUrlRequest> body = null);

        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of PhishingUrlResponseBatch</returns>
        ApiResponse<PhishingUrlResponseBatch> PhishingUrlBatchPostWithHttpInfo (List<PhishingUrlRequest> body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of PhishingUrlAdvancedResponseBatch</returns>
        System.Threading.Tasks.Task<PhishingUrlAdvancedResponseBatch> PhishingUrlAdvancedBatchPostAsync (PhishingUrlAdvancedRequestBatch body = null);

        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingUrlAdvancedResponseBatch)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhishingUrlAdvancedResponseBatch>> PhishingUrlAdvancedBatchPostAsyncWithHttpInfo (PhishingUrlAdvancedRequestBatch body = null);
        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of PhishingUrlResponseBatch</returns>
        System.Threading.Tasks.Task<PhishingUrlResponseBatch> PhishingUrlBatchPostAsync (List<PhishingUrlRequest> body = null);

        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <remarks>
        /// Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingUrlResponseBatch)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhishingUrlResponseBatch>> PhishingUrlBatchPostAsyncWithHttpInfo (List<PhishingUrlRequest> body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PhishingUrlBatchApi : IPhishingUrlBatchApi
    {
        private Cloudmersive.APIClient.NETCore.Phishing.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingUrlBatchApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PhishingUrlBatchApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingUrlBatchApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PhishingUrlBatchApi(Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.Phishing.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat. Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>PhishingUrlAdvancedResponseBatch</returns>
        public PhishingUrlAdvancedResponseBatch PhishingUrlAdvancedBatchPost (PhishingUrlAdvancedRequestBatch body = null)
        {
             ApiResponse<PhishingUrlAdvancedResponseBatch> localVarResponse = PhishingUrlAdvancedBatchPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat. Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of PhishingUrlAdvancedResponseBatch</returns>
        public ApiResponse< PhishingUrlAdvancedResponseBatch > PhishingUrlAdvancedBatchPostWithHttpInfo (PhishingUrlAdvancedRequestBatch body = null)
        {

            var localVarPath = "./phishing/url/advanced/batch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingUrlAdvancedBatchPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingUrlAdvancedResponseBatch>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingUrlAdvancedResponseBatch) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingUrlAdvancedResponseBatch)));
        }

        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat. Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of PhishingUrlAdvancedResponseBatch</returns>
        public async System.Threading.Tasks.Task<PhishingUrlAdvancedResponseBatch> PhishingUrlAdvancedBatchPostAsync (PhishingUrlAdvancedRequestBatch body = null)
        {
             ApiResponse<PhishingUrlAdvancedResponseBatch> localVarResponse = await PhishingUrlAdvancedBatchPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Accept multiple urls at once to perform lookups to see if the urls are known phishing sites as well as multiple other scans to determine  if the URL is a potential phishing threat. Uses advanced AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingUrlAdvancedResponseBatch)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PhishingUrlAdvancedResponseBatch>> PhishingUrlAdvancedBatchPostAsyncWithHttpInfo (PhishingUrlAdvancedRequestBatch body = null)
        {

            var localVarPath = "./phishing/url/advanced/batch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingUrlAdvancedBatchPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingUrlAdvancedResponseBatch>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingUrlAdvancedResponseBatch) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingUrlAdvancedResponseBatch)));
        }

        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat. Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>PhishingUrlResponseBatch</returns>
        public PhishingUrlResponseBatch PhishingUrlBatchPost (List<PhishingUrlRequest> body = null)
        {
             ApiResponse<PhishingUrlResponseBatch> localVarResponse = PhishingUrlBatchPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat. Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of PhishingUrlResponseBatch</returns>
        public ApiResponse< PhishingUrlResponseBatch > PhishingUrlBatchPostWithHttpInfo (List<PhishingUrlRequest> body = null)
        {

            var localVarPath = "./phishing/url/batch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingUrlBatchPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingUrlResponseBatch>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingUrlResponseBatch) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingUrlResponseBatch)));
        }

        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat. Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of PhishingUrlResponseBatch</returns>
        public async System.Threading.Tasks.Task<PhishingUrlResponseBatch> PhishingUrlBatchPostAsync (List<PhishingUrlRequest> body = null)
        {
             ApiResponse<PhishingUrlResponseBatch> localVarResponse = await PhishingUrlBatchPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Accept multiple urls at oncee and perform AI and deterministic methods to detect if a URL is a phishing threat. Uses AI and deterministic methods to detect if a URL is a phishing threat.
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingUrlResponseBatch)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PhishingUrlResponseBatch>> PhishingUrlBatchPostAsyncWithHttpInfo (List<PhishingUrlRequest> body = null)
        {

            var localVarPath = "./phishing/url/batch";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json", 
                "application/xml", 
                "text/xml", 
                "application/_*+xml"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingUrlBatchPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingUrlResponseBatch>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingUrlResponseBatch) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingUrlResponseBatch)));
        }

    }
}
