/* 
 * phishingapi
 *
 * Easily and directly scan and block phishing security threats in input.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp.Portable;
using Cloudmersive.APIClient.NETCore.Phishing.Client;
using Cloudmersive.APIClient.NETCore.Phishing.Model;

namespace Cloudmersive.APIClient.NETCore.Phishing.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPhishingDetectionApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>PhishingDetectionEmailAdvancedResponse</returns>
        PhishingDetectionEmailAdvancedResponse PhishingDetectEmailAdvancedPost (AdvancedEmailDetectionRequest body = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionEmailAdvancedResponse</returns>
        ApiResponse<PhishingDetectionEmailAdvancedResponse> PhishingDetectEmailAdvancedPostWithHttpInfo (AdvancedEmailDetectionRequest body = null);
        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>PhishingDetectionAdvancedResponse</returns>
        PhishingDetectionAdvancedResponse PhishingDetectFileAdvancedPost (string model = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionAdvancedResponse</returns>
        ApiResponse<PhishingDetectionAdvancedResponse> PhishingDetectFileAdvancedPostWithHttpInfo (string model = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>PhishingDetectionResponse</returns>
        PhishingDetectionResponse PhishingDetectFilePost (string model = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionResponse</returns>
        ApiResponse<PhishingDetectionResponse> PhishingDetectFilePostWithHttpInfo (string model = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>PhishingDetectionAdvancedResponse</returns>
        PhishingDetectionAdvancedResponse PhishingDetectTextStringAdvancedPost (PhishingDetectionAdvancedRequest body = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionAdvancedResponse</returns>
        ApiResponse<PhishingDetectionAdvancedResponse> PhishingDetectTextStringAdvancedPostWithHttpInfo (PhishingDetectionAdvancedRequest body = null);
        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>PhishingDetectionUrlAdvancedResponse</returns>
        PhishingDetectionUrlAdvancedResponse PhishingDetectUrlAdvancedPost (AdvancedUrlDetectionRequest body = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionUrlAdvancedResponse</returns>
        ApiResponse<PhishingDetectionUrlAdvancedResponse> PhishingDetectUrlAdvancedPostWithHttpInfo (AdvancedUrlDetectionRequest body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of PhishingDetectionEmailAdvancedResponse</returns>
        System.Threading.Tasks.Task<PhishingDetectionEmailAdvancedResponse> PhishingDetectEmailAdvancedPostAsync (AdvancedEmailDetectionRequest body = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionEmailAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhishingDetectionEmailAdvancedResponse>> PhishingDetectEmailAdvancedPostAsyncWithHttpInfo (AdvancedEmailDetectionRequest body = null);
        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of PhishingDetectionAdvancedResponse</returns>
        System.Threading.Tasks.Task<PhishingDetectionAdvancedResponse> PhishingDetectFileAdvancedPostAsync (string model = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhishingDetectionAdvancedResponse>> PhishingDetectFileAdvancedPostAsyncWithHttpInfo (string model = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of PhishingDetectionResponse</returns>
        System.Threading.Tasks.Task<PhishingDetectionResponse> PhishingDetectFilePostAsync (string model = null, System.IO.Stream inputFile = null);

        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhishingDetectionResponse>> PhishingDetectFilePostAsyncWithHttpInfo (string model = null, System.IO.Stream inputFile = null);
        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of PhishingDetectionAdvancedResponse</returns>
        System.Threading.Tasks.Task<PhishingDetectionAdvancedResponse> PhishingDetectTextStringAdvancedPostAsync (PhishingDetectionAdvancedRequest body = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhishingDetectionAdvancedResponse>> PhishingDetectTextStringAdvancedPostAsyncWithHttpInfo (PhishingDetectionAdvancedRequest body = null);
        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>Task of PhishingDetectionUrlAdvancedResponse</returns>
        System.Threading.Tasks.Task<PhishingDetectionUrlAdvancedResponse> PhishingDetectUrlAdvancedPostAsync (AdvancedUrlDetectionRequest body = null);

        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionUrlAdvancedResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PhishingDetectionUrlAdvancedResponse>> PhishingDetectUrlAdvancedPostAsyncWithHttpInfo (AdvancedUrlDetectionRequest body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PhishingDetectionApi : IPhishingDetectionApi
    {
        private Cloudmersive.APIClient.NETCore.Phishing.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PhishingDetectionApi(String basePath)
        {
            this.Configuration = new Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PhishingDetectionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PhishingDetectionApi(Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Cloudmersive.APIClient.NETCore.Phishing.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloudmersive.APIClient.NETCore.Phishing.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>PhishingDetectionEmailAdvancedResponse</returns>
        public PhishingDetectionEmailAdvancedResponse PhishingDetectEmailAdvancedPost (AdvancedEmailDetectionRequest body = null)
        {
             ApiResponse<PhishingDetectionEmailAdvancedResponse> localVarResponse = PhishingDetectEmailAdvancedPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionEmailAdvancedResponse</returns>
        public ApiResponse< PhishingDetectionEmailAdvancedResponse > PhishingDetectEmailAdvancedPostWithHttpInfo (AdvancedEmailDetectionRequest body = null)
        {

            var localVarPath = "./phishing/detect/email/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectEmailAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionEmailAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionEmailAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionEmailAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of PhishingDetectionEmailAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<PhishingDetectionEmailAdvancedResponse> PhishingDetectEmailAdvancedPostAsync (AdvancedEmailDetectionRequest body = null)
        {
             ApiResponse<PhishingDetectionEmailAdvancedResponse> localVarResponse = await PhishingDetectEmailAdvancedPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input email.  Analyzes input email as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionEmailAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PhishingDetectionEmailAdvancedResponse>> PhishingDetectEmailAdvancedPostAsyncWithHttpInfo (AdvancedEmailDetectionRequest body = null)
        {

            var localVarPath = "./phishing/detect/email/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectEmailAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionEmailAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionEmailAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionEmailAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>PhishingDetectionAdvancedResponse</returns>
        public PhishingDetectionAdvancedResponse PhishingDetectFileAdvancedPost (string model = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<PhishingDetectionAdvancedResponse> localVarResponse = PhishingDetectFileAdvancedPostWithHttpInfo(model, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionAdvancedResponse</returns>
        public ApiResponse< PhishingDetectionAdvancedResponse > PhishingDetectFileAdvancedPostWithHttpInfo (string model = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./phishing/detect/file/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectFileAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of PhishingDetectionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<PhishingDetectionAdvancedResponse> PhishingDetectFileAdvancedPostAsync (string model = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<PhishingDetectionAdvancedResponse> localVarResponse = await PhishingDetectFileAdvancedPostAsyncWithHttpInfo(model, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learning to detect phishing, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model"> (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PhishingDetectionAdvancedResponse>> PhishingDetectFileAdvancedPostAsyncWithHttpInfo (string model = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./phishing/detect/file/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectFileAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>PhishingDetectionResponse</returns>
        public PhishingDetectionResponse PhishingDetectFilePost (string model = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<PhishingDetectionResponse> localVarResponse = PhishingDetectFilePostWithHttpInfo(model, inputFile);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionResponse</returns>
        public ApiResponse< PhishingDetectionResponse > PhishingDetectFilePostWithHttpInfo (string model = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./phishing/detect/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectFilePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionResponse)));
        }

        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of PhishingDetectionResponse</returns>
        public async System.Threading.Tasks.Task<PhishingDetectionResponse> PhishingDetectFilePostAsync (string model = null, System.IO.Stream inputFile = null)
        {
             ApiResponse<PhishingDetectionResponse> localVarResponse = await PhishingDetectFilePostAsyncWithHttpInfo(model, inputFile);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform AI phishing detection and classification on an input image or document (PDF or DOCX).  Analyzes input content as well as embedded URLs with AI deep learnign to detect phishing and other unsafe content.  Uses 100-125 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="model">Model to use; default setting is Advanced (optional, default to Advanced)</param>
        /// <param name="inputFile"> (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PhishingDetectionResponse>> PhishingDetectFilePostAsyncWithHttpInfo (string model = null, System.IO.Stream inputFile = null)
        {

            var localVarPath = "./phishing/detect/file";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "multipart/form-data"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (model != null) localVarHeaderParams.Add("model", this.Configuration.ApiClient.ParameterToString(model)); // header parameter
            if (inputFile != null) localVarFileParams.Add("inputFile", this.Configuration.ApiClient.ParameterToFile("inputFile", inputFile));

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectFilePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionResponse)));
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>PhishingDetectionAdvancedResponse</returns>
        public PhishingDetectionAdvancedResponse PhishingDetectTextStringAdvancedPost (PhishingDetectionAdvancedRequest body = null)
        {
             ApiResponse<PhishingDetectionAdvancedResponse> localVarResponse = PhishingDetectTextStringAdvancedPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionAdvancedResponse</returns>
        public ApiResponse< PhishingDetectionAdvancedResponse > PhishingDetectTextStringAdvancedPostWithHttpInfo (PhishingDetectionAdvancedRequest body = null)
        {

            var localVarPath = "./phishing/detect/text-string/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectTextStringAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of PhishingDetectionAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<PhishingDetectionAdvancedResponse> PhishingDetectTextStringAdvancedPostAsync (PhishingDetectionAdvancedRequest body = null)
        {
             ApiResponse<PhishingDetectionAdvancedResponse> localVarResponse = await PhishingDetectTextStringAdvancedPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against input text string.  Analyzes input content as well as embedded URLs with AI deep learnign to detect spam, phishing and other unsafe content.  Uses 25-100 API calls depending on model selected. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Phishing detection request (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PhishingDetectionAdvancedResponse>> PhishingDetectTextStringAdvancedPostAsyncWithHttpInfo (PhishingDetectionAdvancedRequest body = null)
        {

            var localVarPath = "./phishing/detect/text-string/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectTextStringAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>PhishingDetectionUrlAdvancedResponse</returns>
        public PhishingDetectionUrlAdvancedResponse PhishingDetectUrlAdvancedPost (AdvancedUrlDetectionRequest body = null)
        {
             ApiResponse<PhishingDetectionUrlAdvancedResponse> localVarResponse = PhishingDetectUrlAdvancedPostWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>ApiResponse of PhishingDetectionUrlAdvancedResponse</returns>
        public ApiResponse< PhishingDetectionUrlAdvancedResponse > PhishingDetectUrlAdvancedPostWithHttpInfo (AdvancedUrlDetectionRequest body = null)
        {

            var localVarPath = "./phishing/detect/url/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectUrlAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionUrlAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionUrlAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionUrlAdvancedResponse)));
        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>Task of PhishingDetectionUrlAdvancedResponse</returns>
        public async System.Threading.Tasks.Task<PhishingDetectionUrlAdvancedResponse> PhishingDetectUrlAdvancedPostAsync (AdvancedUrlDetectionRequest body = null)
        {
             ApiResponse<PhishingDetectionUrlAdvancedResponse> localVarResponse = await PhishingDetectUrlAdvancedPostAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Perform advanced AI phishing detection and classification against an input URL.  Retrieves the URL content, checks for SSRF threats, and analyzes the page with AI deep learning to detect phishing and other unsafe content.  Uses 100-125 API calls. 
        /// </summary>
        /// <exception cref="Cloudmersive.APIClient.NETCore.Phishing.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">URL phishing detection request (optional)</param>
        /// <returns>Task of ApiResponse (PhishingDetectionUrlAdvancedResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<PhishingDetectionUrlAdvancedResponse>> PhishingDetectUrlAdvancedPostAsyncWithHttpInfo (AdvancedUrlDetectionRequest body = null)
        {

            var localVarPath = "./phishing/detect/url/advanced";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/_*+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain",
                "application/json",
                "text/json"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }

            // authentication (Apikey) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Apikey")))
            {
                localVarHeaderParams["Apikey"] = this.Configuration.GetApiKeyWithPrefix("Apikey");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("PhishingDetectUrlAdvancedPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<PhishingDetectionUrlAdvancedResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Key, x => x.Value.ToString()),
                (PhishingDetectionUrlAdvancedResponse) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(PhishingDetectionUrlAdvancedResponse)));
        }

    }
}
